package cc.pineclone.eventflow.plugin.trigger.jnativehook.filter;

import cc.pineclone.eventflow.interaction.NeuKeySpec;
import cc.pineclone.eventflow.interaction.NeuModifierConstraint;
import cc.pineclone.eventflow.interaction.api.InteractionSpecAdapter;
import cc.pineclone.eventflow.interaction.exception.InteractionSpecAdapteeException;
import cc.pineclone.eventflow.plugin.trigger.jnativehook.api.JNativeHookKeySpec;

import java.util.EnumMap;
import java.util.Map;

import static com.github.kwhat.jnativehook.keyboard.NativeKeyEvent.*;

public class NeuKeySpecFilter extends KeySpecFilter<NeuKeySpec, NeuModifierConstraint> {

    private static final Map<NeuKeySpec.NeuKey, Integer> NEUTRAL_TO_JNATIVEHOOK_KEY_MAP = new EnumMap<>(NeuKeySpec.NeuKey.class) {{
        put(ESCAPE, VC_ESCAPE);
        put(F1, VC_F1);
        put(F2, VC_F2);
        put(F3, VC_F3);
        put(F4, VC_F4);
        put(F5, VC_F5);
        put(F6, VC_F6);
        put(F7, VC_F7);
        put(F8, VC_F8);
        put(F9, VC_F9);
        put(F10, VC_F10);
        put(F11, VC_F11);
        put(F12, VC_F12);
        put(F13, VC_F13);
        put(F14, VC_F14);
        put(F15, VC_F15);
        put(F16, VC_F16);
        put(F17, VC_F17);
        put(F18, VC_F18);
        put(F19, VC_F19);
        put(F20, VC_F20);
        put(F21, VC_F21);
        put(F22, VC_F22);
        put(F23, VC_F23);
        put(F24, VC_F24);
        put(BACKQUOTE, VC_BACKQUOTE);
        put(NUM_1, VC_1);
        put(NUM_2, VC_2);
        put(NUM_3, VC_3);
        put(NUM_4, VC_4);
        put(NUM_5, VC_5);
        put(NUM_6, VC_6);
        put(NUM_7, VC_7);
        put(NUM_8, VC_8);
        put(NUM_9, VC_9);
        put(NUM_0, VC_0);
        put(MINUS, VC_MINUS);
        put(EQUALS, VC_EQUALS);
        put(BACKSPACE, VC_BACKSPACE);
        put(TAB, VC_TAB);
        put(CAPS_LOCK, VC_CAPS_LOCK);
        put(A, VC_A);
        put(B, VC_B);
        put(C, VC_C);
        put(D, VC_D);
        put(E, VC_E);
        put(F, VC_F);
        put(G, VC_G);
        put(H, VC_H);
        put(I, VC_I);
        put(J, VC_J);
        put(K, VC_K);
        put(L, VC_L);
        put(M, VC_M);
        put(N, VC_N);
        put(O, VC_O);
        put(P, VC_P);
        put(Q, VC_Q);
        put(R, VC_R);
        put(S, VC_S);
        put(T, VC_T);
        put(U, VC_U);
        put(V, VC_V);
        put(W, VC_W);
        put(X, VC_X);
        put(Y, VC_Y);
        put(Z, VC_Z);
        put(OPEN_BRACKET, VC_OPEN_BRACKET);
        put(CLOSE_BRACKET, VC_CLOSE_BRACKET);
        put(BACK_SLASH, VC_BACK_SLASH);
        put(SEMICOLON, VC_SEMICOLON);
        put(QUOTE, VC_QUOTE);
        put(ENTER, VC_ENTER);
        put(COMMA, VC_COMMA);
        put(PERIOD, VC_PERIOD);
        put(SLASH, VC_SLASH);
        put(SPACE, VC_SPACE);
        put(PRINT_SCREEN, VC_PRINTSCREEN);
        put(SCROLL_LOCK, VC_SCROLL_LOCK);
        put(PAUSE, VC_PAUSE);
        put(INSERT, VC_INSERT);
        put(DELETE, VC_DELETE);
        put(HOME, VC_HOME);
        put(END, VC_END);
        put(PAGE_UP, VC_PAGE_UP);
        put(PAGE_DOWN, VC_PAGE_DOWN);
        put(UP, VC_UP);
        put(LEFT, VC_LEFT);
        put(CLEAR, VC_CLEAR);
        put(RIGHT, VC_RIGHT);
        put(DOWN, VC_DOWN);
        put(NUM_LOCK, VC_NUM_LOCK);
        put(SEPARATOR, VC_SEPARATOR);
        put(SHIFT, VC_SHIFT);
        put(CONTROL, VC_CONTROL);
        put(ALT, VC_ALT);
        put(META, VC_META);
        put(CONTEXT_MENU, VC_CONTEXT_MENU);
        put(POWER, VC_POWER);
        put(SLEEP, VC_SLEEP);
        put(WAKE, VC_WAKE);
        put(MEDIA_PLAY, VC_MEDIA_PLAY);
        put(MEDIA_STOP, VC_MEDIA_STOP);
        put(MEDIA_PREVIOUS, VC_MEDIA_PREVIOUS);
        put(MEDIA_NEXT, VC_MEDIA_NEXT);
        put(MEDIA_SELECT, VC_MEDIA_SELECT);
        put(MEDIA_EJECT, VC_MEDIA_EJECT);
        put(VOLUME_MUTE, VC_VOLUME_MUTE);
        put(VOLUME_UP, VC_VOLUME_UP);
        put(VOLUME_DOWN, VC_VOLUME_DOWN);
        put(APP_MAIL, VC_APP_MAIL);
        put(APP_CALCULATOR, VC_APP_CALCULATOR);
        put(APP_MUSIC, VC_APP_MUSIC);
        put(APP_PICTURES, VC_APP_PICTURES);
        put(BROWSER_SEARCH, VC_BROWSER_SEARCH);
        put(BROWSER_HOME, VC_BROWSER_HOME);
        put(BROWSER_BACK, VC_BROWSER_BACK);
        put(BROWSER_FORWARD, VC_BROWSER_FORWARD);
        put(BROWSER_STOP, VC_BROWSER_STOP);
        put(BROWSER_REFRESH, VC_BROWSER_REFRESH);
        put(BROWSER_FAVORITES, VC_BROWSER_FAVORITES);
        put(KATAKANA, VC_KATAKANA);
        put(FURIGANA, VC_FURIGANA);
        put(KANJI, VC_KANJI);
        put(HIRAGANA, VC_HIRAGANA);
        put(YEN, VC_YEN);
        put(SUN_HELP, VC_SUN_HELP);
        put(SUN_STOP, VC_SUN_STOP);
        put(SUN_PROPS, VC_SUN_PROPS);
        put(SUN_FRONT, VC_SUN_FRONT);
        put(SUN_OPEN, VC_SUN_OPEN);
        put(SUN_FIND, VC_SUN_FIND);
        put(SUN_AGAIN, VC_SUN_AGAIN);
        put(SUN_UNDO, VC_SUN_UNDO);
        put(SUN_COPY, VC_SUN_COPY);
        put(SUN_INSERT, VC_SUN_INSERT);
        put(SUN_CUT, VC_SUN_CUT);
        put(UNDEFINED, VC_UNDEFINED);
    }};

    private static final InteractionSpecAdapter<NeuKeySpec, JNativeHookKeySpec> NEU_SPEC_ADAPTER = neuKeySpec -> {
        Integer keyCode = NEUTRAL_TO_JNATIVEHOOK_KEY_MAP.get(neuKeySpec.key());
        if (keyCode == null) throw new InteractionSpecAdapteeException("Unsupported key: " + neuKeySpec.key());

        int keyLocation = switch (neuKeySpec.keyLocation()) {
            case UNKNOWN -> KEY_LOCATION_UNKNOWN;
            case STANDARD -> KEY_LOCATION_STANDARD;
            case LEFT -> KEY_LOCATION_LEFT;
            case RIGHT -> KEY_LOCATION_RIGHT;
            case NUMPAD -> KEY_LOCATION_NUMPAD;
        };

        return new JNativeHookKeySpec(keyCode, keyLocation);
    };

    public NeuKeySpecFilter(NeuKeySpec scope, NeuModifierConstraint modifier) {
        super(scope, NEU_SPEC_ADAPTER, modifier, NeuModifierAdapter.getINSTANCE());
    }
}
